### ISSUE TITLE
Python learning resources -SARAdatascraping

### ISSUE THREAD

**Issue by stoyelq** [dfo-mar-odis/saraDataScraping#18]
### Proposed Change/Activity
Identify a list of good learning materials for Python.

### Why is this important
Have a go-to list of resources to point newer python developers too.

### When is this done?
When there is a linked list below with resources for basic python, pandas and object oriented programming (OOP).  

### Perceived Effort
3

### Learning resources

- [Python basics](https://diveintopython3.net/) (Chapters 0-4)
- [OOP tutorial](https://realpython.com/python3-object-oriented-programming/)
- [Pandas](https://pandas.pydata.org/docs/user_guide/10min.html)

**Comment by stoyelq** [comment]
@gomezcatalina, that should be enough to get you rolling, definitely reach out once you start and I can help with the installing/setup if you run into issues.

**Comment by gomezcatalina** [comment]
Great resources! Really enjoyed OPP.
