### ISSUE TITLE
Sprint #1 - Review & Retrospective - SARADataScraping

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/saraDataScraping#20]
## Proposed Change/Activity
Communicate outputs of Sprint #1

## Why is this important
Communication is key to make sure product owners continue to advance their vision, and to make sure we can plan next spring appropriately   

## Actions

- [x] Catalina to draft update: https://086gc.sharepoint.com/:w:/r/sites/MaritimesSpatialPlanning-MAROpenDataLogistics/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B1d8273cc-d3f2-45c9-91ae-e0a9d8c98c0b%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL
- [x] Quentin to review/approve
- [x] Catalina to update calendar invite
- [x] Quentin to prepare verbal presentation for Sprint Review on September 28 2022
- [x] Catalina & Quentin to debrief: what went right, what could have gone better, and what can be made better in the next Sprint. 
- [x] Clean up tickets/ make a new backlog

**Comment by stoyelq** [comment]
I've cleaned up the old tickets.  There are a couple items in the To-Do list that are good for immediate work, but we will hopefully be able to add some more following the meeting with Julie on October 5th.
