### ISSUE TITLE
project-wrap-up-SARAdatascraping

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/saraDataScraping#34]
# Proposed Activity

To wrap up SARA project in Liu of Quentin's departure 

# Why is this important?

Important to give closure and celebrate where things are at the moment, and decide on next steps

# Action Items

- [x] Sam to confirm whether tool works on his end 
- [x] Catalina to draft final summary email/package to be sent to SARA folks to inform them of wrap up of project and next steps
 - [x] @stoyelq  to review report [here](https://086gc.sharepoint.com/:w:/r/sites/MaritimesSpatialPlanning-MAROpenDataLogistics/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B7ddfb8bb-c6b6-4372-8b63-b229c9cd70ce%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1), and add links to video/demo of the tool and manual he developed for Sam
- [x] Quentin & Catalina to present package to Tana for her advice 
- [x] Tana, Catalina & Quentin to explore next steps: 1) bring a R coder onboard to go ahead with Reproducible Reporting templates for SARA, or, 2) use remaining funds for other purposes, and 3) to explore how to communicate this to Carolyne B. 
- [x] Catalina to email package to Carolyne Bakelaar et al.

**Comment by stoyelq** [comment]
Links are in the final report, but I still need to go over some things for the third objective.

-All done reviewing the report now
